# Generated by Django 3.2.5 on 2021-07-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechSup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='cityname',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='population',
            new_name='citypopulation',
        ),
    ]
