# Generated by Django 3.2.5 on 2021-07-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechSup', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
