# Generated by Django 3.2.5 on 2021-07-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechSup', '0002_auto_20210715_0840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='viewgraph',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='cityname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='citypopulation',
            new_name='population',
        ),
    ]
