# Generated by Django 3.2.5 on 2021-07-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechSup', '0004_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
